# Pinned Versions
GO_VERSION=1.15.3
ALPINE_VERSION=3.12.0
GOLANGCI_LINT_VERSION=v1.31.0-alpine
GOTESTSUM_VERSION=0.5.2

GOOS?=$(shell go env GOOS)
GOARCH?=$(shell go env GOARCH)
BINARY_EXT=
ifeq ($(GOOS),windows)
    BINARY_EXT=.exe
endif
BINARY_NAME=hub-tool
PLATFORM_BINARY:=$(BINARY_NAME)_$(GOOS)_$(GOARCH)$(BINARY_EXT)
BINARY=$(BINARY_NAME)$(BINARY_EXT)
