name: Build PR
on: [pull_request]

jobs:
  lint:
    name: Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Check license headers
        run: make validate

      - name: Run golangci-lint
        run: make lint

  build-linux:
    name: Build Linux
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      E2E_HUB_USERNAME: ${{ secrets.E2E_HUB_USERNAME }}
      E2E_HUB_TOKEN: ${{ secrets.E2E_HUB_TOKEN }}
    steps:
      - name: Docker version
        run: docker version

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Build CLI
        run: make build

      - name: Unit Tests
        run: make test-unit

      - name: End-to-end Tests
        run: make e2e
